import mongoose, { Document, Schema } from 'mongoose';

/**
 * Security Alert Model
 * Stores real-time security alerts generated by monitoring thresholds.
 * Alerts are triggered when suspicious activity patterns are detected.
 */

export interface ISecurityAlert extends Document {
    type: 'brute_force' | 'ip_blocked' | 'account_locked' | 'suspicious_activity' | 'rate_limit_exceeded';
    severity: 'low' | 'medium' | 'high' | 'critical';
    message: string;
    details: {
        ip?: string;
        userId?: string;
        userEmail?: string;
        endpoint?: string;
        attemptCount?: number;
        [key: string]: any;
    };
    acknowledged: boolean;
    acknowledgedBy?: string;
    acknowledgedAt?: Date;
    createdAt: Date;
}

const SecurityAlertSchema = new Schema({
    type: {
        type: String,
        enum: ['brute_force', 'ip_blocked', 'account_locked', 'suspicious_activity', 'rate_limit_exceeded'],
        required: true
    },
    severity: {
        type: String,
        enum: ['low', 'medium', 'high', 'critical'],
        required: true
    },
    message: { type: String, required: true },
    details: {
        ip: String,
        userId: { type: Schema.Types.ObjectId, ref: 'User' },
        userEmail: String,
        endpoint: String,
        attemptCount: Number
    },
    acknowledged: { type: Boolean, default: false },
    acknowledgedBy: { type: Schema.Types.ObjectId, ref: 'User' },
    acknowledgedAt: { type: Date }
}, { timestamps: true });

// Index for efficient querying
SecurityAlertSchema.index({ createdAt: -1 });
SecurityAlertSchema.index({ type: 1, acknowledged: 1 });
SecurityAlertSchema.index({ severity: 1 });

// TTL index: auto-delete acknowledged alerts after 30 days
SecurityAlertSchema.index({ acknowledgedAt: 1 }, { expireAfterSeconds: 2592000, partialFilterExpression: { acknowledged: true } });

export const SecurityAlert = mongoose.model<ISecurityAlert>('SecurityAlert', SecurityAlertSchema);
